# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The PhotoEditor SDK Docs for HTML5, iOS and Android by Img.ly
email: contact@photoeditorsdk.com
description: > # this means to ignore newlines until "baseurl:"
  The PhotoEditor SDK is a fully customizable mean machine. Start your free trial and integrate the versatile editor into your own HTML5, iOS or Android app
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docs.photoeditorsdk.com" # the base hostname & protocol for you
name: "PhotoEditor SDK Documentation"
keywords: "photo, editor, android, ios, html5, image, editing, canvas, javascript"
prefix: "PhotoEditor SDK"

image: https://www.photoeditorsdk.com/assets/images/meta-image.jpg
twitter_username: imgly
github_username:  imgly

sass:
  sass_dir: _sass

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist

whitelist:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-sitemap
# include: ['_pages']

host: 0.0.0.0
port: 5000

Include: ['_features', '_quickstarts', '_guides']

# Build settings
markdown: kramdown

kramdown:
  input: GFM

collections:
  features:
    output: true
    permalink: /:collection/:path
  quickstarts:
    output: true
    permalink: /:collection/:path
  guides:
    output: true
    permalink: /:collection/:path
  apidocs:
    output: true
    permalink: /:collection/:path



defaults:
# HTML5
  - scope:
      path: "guides/html5"
      collection: guides
    values:
      platform: html5
      layout: guides/content
      description: "A quick guide on how to easily get started with the PhotoEditor SDK for HTML5. Your kick-off to delight your users with top-notch editing capabilities."

  - scope:
      path: "guides/html5/v3_6"
    values:
      version: v3_6

# IOS
  - scope:
      path: "guides/ios"
      collection: guides
    values:
      platform: ios
      layout: guides/content
      prefix: "PhotoEditor SDK | iOS "
      description: "A quick guide on how to easily get started with the PhotoEditor SDK for iOS. Your kick-off to delight your users with top-notch editing capabilities."
  - scope:
      path: "guides/ios/v7_1"
      collection: guides
    values:
      version: v7_1

# Android
  - scope:
      path: "guides/android"
      collection: guides
    values:
      platform: android
      layout: guides/content
      description: "A quick guide on how to easily get started with the PhotoEditor SDK for Android. Your kick-off to delight your users with top-notch editing capabilities."
  - scope:
      path: "guides/android/v3_1"
      collection: guides
    values:
      version: v3_1

# quickstarts
  - scope:
      path: "quickstarts"
      collection: quickstarts
    values:
      layout: quickstarts/content
      description: "View our Quickstarts Guides for integrating the PhotoEditor SDK for specific framesworks such as Ionic, React Native, Cordova, Rails or Ruby Gem"

# features
  - scope:
      path: "features"
      collection: features
    values:
      layout: features/content
      description: "Learn more about the key features of the PhotoEditor SDK such as Filters, Transform, Text, Stickers, Adjustements or Brush"
